bar:
  colors:
    background: grey
    fill: orange
    fill_done: green
entries:
  defaults:
    arrival: vandaag 04:20:00
    ms: 0
    walktime: 00:00:00
ghub:
  link: https://github.com/Zeepaardje98/Bottenkraker-Timer
selected_theme: cacturne
themes:
  cacturne:
    background: '#0E1013'
    border: '#ACDF87'
    button: '#1E5631'
    entry: '#1E5631'
    entry_wrong: '#E8A19C'
    ghub_im: images/Ghub_logo_green.png
    primary: '#519839'
    settings_im: images/settings_green.png
    text: '#FFFFFF'
  dark:
    background: '#0E1013'
    border: '#17181B'
    button: '#202124'
    entry: '#282A2D'
    entry_wrong: '#E8A19C'
    ghub_im: images/Ghub_logo_light.png
    primary: '#6200EE'
    settings_im: images/settings_light.png
    text: '#FFFFFF'
timesync:
  selected: pool.ntp.org
  servers:
    pool.ntp.org:
      delay: 85
      image: images/TW.PNG
    standard:
      delay: 0
      image: ''
