bar:
  colors:
    background: grey
    fill: orange
    fill_done: green
entries:
  defaults:
    arrival: vandaag 04:20:00
    ms: 0
    walktime: 00:00:00
  right_color: white
  wrong_color: '#E8A19C'
ghub:
  image: images/Ghub_logo_dark.png
  link: https://github.com/Zeepaardje98/Bottenkraker-Timer
selected_theme: default
themes:
  dark:
    background: '#121212'
    border: '#000000'
    text: '#FFFFFF'
  default:
    background: None
    border: None
    text: None
timesync:
  selected: standard
  servers:
    pool.ntp.org:
      delay: 85
      image: images/TW.PNG
    standard:
      delay: 0
      image: ''
