bar:
  colors:
    background: grey
    fill: orange
    fill_done: green
entries:
  right_color: white
  wrong_color: '#E8A19C'
  defaults:
    arrival: vandaag 23:00:00
    ms: 0
    walktime: 00:14:00
ghub:
  image: images/Ghub_logo_dark.png
  link: https://github.com/Zeepaardje98/Bottenkraker-Timer
theme: dark
timesync:
  selected: pool.ntp.org
  servers:
    pool.ntp.org:
      delay: 85
      image: images/TW.PNG
    standard:
      delay: 0
      image: ''
