bar:
  colors:
    background: grey
    fill: orange
    fill_done: green
timesync:
  selected: pool.ntp.org
  servers:
    pool.ntp.org:
      delay: 85
      image: images/TW.PNG
    standard:
      delay: 0
      image: ''
